export const REPOSITORY_CONSTANTS = {
	USER_REPOSITORY: 'USER_REPOSITORY',
	PROFILE_REPOSITORY: 'PROFILE_REPOSITORY',
	AUDIT_LOG_REPOSITORY: 'AUDIT_LOG_REPOSITORY',
	ROLE_REPOSITORY: 'ROLE_REPOSITORY',
	TOKEN_REPOSITORY: 'TOKEN_REPOSITORY',
	CODE_REPOSITORY: 'CODE_REPOSITORY',
	TRACKING_REPOSITORY: 'TRACKING_REPOSITORY',
	PRODUCT_REPOSITORY: 'PRODUCT_REPOSITORY',
	RECIPE_TYPE_REPOSITORY: 'RECIPE_TYPE_REPOSITORY',
	RECIPE_REPOSITORY: 'RECIPE_REPOSITORY',
	REVIEW_REPOSITORY: 'REVIEW_REPOSITORY',
	FAVORITE_REPOSITORY: 'FAVORITE_REPOSITORY',
} as const;

export const PROVIDER_CONSTANTS = {
	DATA_SOURCE: 'DATA_SOURCE',
	PINO_LOGGER: 'PINO_LOGGER',
	CODE_SERVICE: 'CODE_SERVICE',
	SEND_CODE_PROVIDER: 'SEND_CODE_PROVIDER',
	MAILER_PROVIDER: 'MAILER_PROVIDER',
	HTML_TEMPLATE_READER: 'HTML_TEMPLATE_READER',
	REACT_EMAIL_RENDERER: 'REACT_EMAIL_RENDERER',
} as const;

